### ISSUE TITLE
Infinite loop in force_update if a response is not received

### ISSUE THREAD

**Issue by andnic** [ug-cp/precise_sntp#6]
I've encountered an infinite loop while waiting for a response when either the request or response were lost/dropped.

It appears the intention was to wait up to 1000ms for a response, patch attached.

[infinite-loop.patch](https://github.com/ug-cp/precise_sntp/files/10500255/infinite-loop.patch)

**Comment by daniel-mohr** [comment]
Thank you for the first issue! 😉

Sorry, for the very late response -- I missed the notification somehow.

And thanks for the patch, it makes it very clear!

**Comment by daniel-mohr** [comment]
Your patch works perfectly. Thanks!
